# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduce', models.TextField(blank=True)),
                ('picture', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('rent', models.IntegerField(default=1000)),
                ('rent_type', models.CharField(blank=True, max_length=200)),
                ('house', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('community', models.TextField(blank=True, default='')),
                ('circum', models.TextField(blank=True, default='')),
                ('translate', models.TextField(blank=True, default='')),
                ('installations', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('houseIntroduce', models.TextField()),
                ('distance', models.IntegerField(default=500)),
                ('housetype', models.CharField(blank=True, choices=[('四室两厅两卫', '四室两厅两卫'), ('三室一厅一卫', '三室一厅一卫'), ('一室一厅一卫', '一室一厅一卫'), ('三室一厅两卫', '三室一厅两卫'), ('二室一厅一卫', '二室一厅一卫'), ('三室两厅两卫', '三室两厅两卫')], max_length=200)),
                ('pic_max', models.ImageField(upload_to='house_pic')),
                ('pic_1', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_2', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_3', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_4', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_5', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_6', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_7', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_8', models.ImageField(blank=True, upload_to='house_pic')),
                ('pic_9', models.ImageField(blank=True, upload_to='house_pic')),
                ('area_to', models.ManyToManyField(related_name='area_to', to='workapp.Area')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='侯爵', max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('保密', '保密'), ('女', '女'), ('男', '男')], default='保密', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.ImageField(default='avatar/wenhao/jpg', upload_to='avatar')),
                ('belong_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collect',
            name='house_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_title', to='workapp.HouseInfo'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='workapp.UserInfo'),
        ),
    ]
