# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_auto_20161125_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('三室一厅一卫', '三室一厅一卫'), ('三室一厅两卫', '三室一厅两卫'), ('三室两厅两卫', '三室两厅两卫'), ('四室两厅两卫', '四室两厅两卫'), ('二室一厅一卫', '二室一厅一卫'), ('一室一厅一卫', '一室一厅一卫')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
