# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_auto_20161125_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseinfo',
            options={'ordering': ['rent']},
        ),
        migrations.RenameField(
            model_name='houseinfo',
            old_name='rent_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('一室一厅一卫', '一室一厅一卫'), ('三室一厅一卫', '三室一厅一卫'), ('二室一厅一卫', '二室一厅一卫'), ('三室两厅两卫', '三室两厅两卫'), ('三室一厅两卫', '三室一厅两卫'), ('四室两厅两卫', '四室两厅两卫')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('保密', '保密'), ('女', '女'), ('男', '男')], default='保密', max_length=10),
        ),
    ]
