# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_auto_20161126_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='yydate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='yytime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('一室一厅一卫', '一室一厅一卫'), ('二室一厅一卫', '二室一厅一卫'), ('三室一厅两卫', '三室一厅两卫'), ('三室一厅一卫', '三室一厅一卫'), ('三室两厅两卫', '三室两厅两卫'), ('四室两厅两卫', '四室两厅两卫')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('女', '女'), ('保密', '保密'), ('男', '男')], default='保密', max_length=10),
        ),
    ]
