# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0009_auto_20161126_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='yydate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='houseinfo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='appoint_h', to='workapp.HouseInfo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='userinfo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='appoint_u', to='workapp.UserInfo'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(blank=True, choices=[('四室两厅两卫', '四室两厅两卫'), ('三室一厅两卫', '三室一厅两卫'), ('一室一厅一卫', '一室一厅一卫'), ('二室一厅一卫', '二室一厅一卫'), ('三室两厅两卫', '三室两厅两卫'), ('三室一厅一卫', '三室一厅一卫')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('保密', '保密')], default='保密', max_length=10),
        ),
    ]
